apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: orders-extension
  name: orders-extension
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-extension
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orders-extension
    spec:
      containers:
      - image: gabbi/orders-extension:0.0.1 # change it to your image
        name: orders-extension
        resources: {}
        ports:
          - containerPort: 8080
        env:
          - name: GATEWAY_URL
            value: $(SAP_COMMERCE_CLOUD_COMMERCE_WEBSERVICES_0229C59F_778E_4E5C_9D65_DB237D9434A1_GATEWAY_URL)
          - name: BASE_SITE
            value: electronics
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: orders-extension
  name: orders-extension
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: orders-extension
  type: ClusterIP
status:
  loadBalancer: {}