apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: ServiceBindingUsage
metadata:
  name: orders-extension-sbu
spec:
  parameters:
    envPrefix:
      name: ""
  serviceBindingRef:
    name: modest-wescoff
  usedBy:
    kind: deployment
    name: orders-extension
