apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: {{ include "order-created.fullname" . }}
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.{{ .Values.global.sources.commerce.name }}.order.created.v1
  protocol: ""
  protocolsettings: {}
  sink: http://{{ include "order-created.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local