apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: {{ include "get-orders.fullname" . }}
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: get-orders-{{ .Release.Namespace }}
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - GET
    path: /.*
    service:
      name: {{ include "get-orders.fullname" . }}
      port: 80
status: {}