apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: {{ include "get-orders.fullname" . }}
spec:
  runtime: nodejs16
  source:
    gitRepository:
      url: {{ .Values.global.repository.url }}
      baseDir: /functions/get-orders
      reference: main
  env:
  - name: REDIS_HOST
    value: {{ printf "%s-redis" .Release.Name }}
  - name: REDIS_PORT
    value: "6379"
