apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: {{ include "orders-extension.fullname" . }}
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: orders-extension-{{ .Release.Namespace }}
  rules:
    - accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
        - POST
        - PUT
        - DELETE
      path: /.*
      service:
        name: {{ include "orders-extension.fullname" . }}
        port: 80