apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: ServiceBindingUsage
metadata:
  name: {{ include "orders-extension.fullname" . }}
spec:
  parameters:
    envPrefix:
      name: ""
  serviceBindingRef:
    name: {{ .Values.global.bindings.ccv2.occ.ref }}
  usedBy:
    kind: deployment
    name: {{ include "orders-extension.fullname" . }}
