# This is a basic workflow to help you get started with Actions

name: DEPLOY TO DEV

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      NAMESPACE: ci-cd-dev
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.DEV_KUBECONFIG }}
      - name: Test kubectl
        run: kubectl -n $NAMESPACE get deployment
      - name: Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'extensions/orders-extension/k8s/api-rule.yaml'
        env:
          spec.service.host: orders-extension-${{ env.NAMESPACE }}
      - uses: Azure/k8s-deploy@v1.3
        name: Deploy Orders Extension
        with:
          manifests: |
            extensions/orders-extension/k8s/deployment.yaml
            extensions/orders-extension/k8s/event-trigger.yaml
            extensions/orders-extension/k8s/service-binding-usage.yaml
            extensions/orders-extension/k8s/api-rule.yaml
          namespace: ${{ env.NAMESPACE }}
