# This is a basic workflow to help you get started with Actions

name: promote-to-prod

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-orders-extension:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      NAMESPACE: ci-cd-prod
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.PROD_KUBECONFIG }}
      - uses: azure/setup-helm@v1
        with:
          version: 'v3.5.1'
      - name: Helm Deployment
        working-directory: extensions/orders-extension/helm-chart/orders-extension
        run: helm install orders-extension . -f ./values-prod.yaml --dry-run --debug
      - name: Run smoke tests on prod environment
        run: echo "running smoke tests"
